export let stocks=[
    {
        "symbol": "A",
        "name": "Agilent Technologies Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "1.0000"
    },
    {
        "symbol": "AAPL",
        "name": "Apple Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.5000"
    },
    {
        "symbol": "AMD",
        "name": "Advanced Micro Devices Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.5000"
    },
    {
        "symbol": "AMZN",
        "name": "Amazon.com Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
    {
        "symbol": "ACB",
        "name": "Aurora Cannabis Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
    {
        "symbol": "T",
        "name": "AT&T Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
    {
        "symbol": "ABBV",
        "name": "AbbVie Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
    {
        "symbol": "MO",
        "name": "Altria Group Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
    {
        "symbol": "BABA",
        "name": "Alibaba Group Holding Limited",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.2000"
    },
    {
        "symbol": "AMRN",
        "name": "Amarin Corporation plc",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.1053"
    }, 
    {
        "symbol": "B",
        "name": "Barnes Group Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "1.0000"
    },
    {
        "symbol": "BABA",
        "name": "Alibaba Group Holding Limited",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.6667"
    },
    {
        "symbol": "BAC",
        "name": "Bank of America Corporation",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.6667"
    },
    {
        "symbol": "BA",
        "name": "The Boeing Company",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.6667"
    },
    {
        "symbol": "BMY",
        "name": "Bristol-Myers Squibb Company",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.6667"
    },
    {
        "symbol": "BE",
        "name": "Bloom Energy Corporation",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.5000"
    },
    {
        "symbol": "BJ",
        "name": "BJ's Wholesale Club Holdings Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.5000"
    },
    {
        "symbol": "BV",
        "name": "BrightView Holdings Inc.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.5000"
    },
    {
        "symbol": "BRY",
        "name": "Berry Petroleum Corporation",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
    {
        "symbol": "BSVN",
        "name": "Bank7 Corp.",
        "type": "Equity",
        "region": "United States",
        "marketOpen": "09:30",
        "marketClose": "16:00",
        "timezone": "UTC-05",
        "currency": "USD",
        "matchScore": "0.4000"
    },
     {
            "symbol": "C",
            "name": "Citigroup Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "1.0000"
        },
        {
            "symbol": "CGC",
            "name": "Canopy Growth Corporation",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.5000"
        },
        {
            "symbol": "CRON",
            "name": "Cronos Group Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.5000"
        },
        {
            "symbol": "CTL",
            "name": "CenturyLink Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.5000"
        },
        {
            "symbol": "CWK",
            "name": "Cushman & Wakefield plc",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.5000"
        },
        {
            "symbol": "CHK",
            "name": "Chesapeake Energy Corporation",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.5000"
        },
        {
            "symbol": "CNST",
            "name": "Constellation Pharmaceuticals Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.4000"
        },
        {
            "symbol": "CTK",
            "name": "CooTek (Cayman) Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.4000"
        },
        {
            "symbol": "CRNX",
            "name": "Crinetics Pharmaceuticals Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.4000"
        },
        {
            "symbol": "CBNK",
            "name": "Capital Bancorp Inc.",
            "type": "Equity",
            "region": "United States",
            "marketOpen": "09:30",
            "marketClose": "16:00",
            "timezone": "UTC-05",
            "currency": "USD",
            "matchScore": "0.4000"
        }
]